### ISSUE TITLE
WebpackError: _react2.default.createRef is not a function

### ISSUE THREAD

**Issue by JWeis** [jacobp100/react-twentytwenty#14]
I am using this with Gatsby V1 and have been for a few months now. I am trying to rebuild my site and I am running into this error: 

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  50 |     _this.onDragMove = _this.onDragMove.bind(_this);
  51 |
> 52 |     _this.container = _react2.default.createRef();
     | ^
  53 |     return _this;
  54 |   }
  55 |


  WebpackError: _react2.default.createRef is not a function

  - index.js:52 new TwentyTwenty
    ~/react-twentytwenty/index.js:52:1
```

Please help.

**Comment by jacobp100** [comment]
Are you using npm or yarn (or other)?

A quick fix is to install react-twentytwenty v1.1.0 or upgrade react to >16.3.0

**Comment by jacobp100** [comment]
Did this fix your issue?

**Comment by JWeis** [comment]
Thanks for the follow-up!

I am pretty sure the issue is with Gatsby V1. I am using their plugin to use React 16 in V1, although I think this currently goes up to 16.0. 

I have removed twenty-twenty from this project for now. When I upgrade this project to V2, it should work fine as React is a peer dependency in V2 and I can install any version needed.

**Comment by jacobp100** [comment]
I just had a thought on how to support older versions. If you still wanted to use this library, could you try,

```
npm install https://github.com/jacobp100/react-twentytwenty#jacobp100-patch-1
```
